%Option to import (1-3) or 7 solar irradiance & raw plant data

%Also includes solar coefficents to be used to asses impacts on VRD
%Import SOLAR FILES
addpath(PV_Site_path);
%PV_Site_path generated by GUI

if PV_Site == 1
    load M_SHELBY_INFO.mat
    M_PVSITE_INFO.RR_distrib = M_SHELBY_INFO.RR_distrib;
    M_PVSITE_INFO.kW = M_SHELBY_INFO.kW;
    M_PVSITE_INFO.name = M_SHELBY_INFO.name;
    M_PVSITE_INFO.VI = M_SHELBY_INFO.VI;
    M_PVSITE_INFO.CI = M_SHELBY_INFO.CI;
    load M_SHELBY.mat
    for i=1:1:12
        M_PVSITE(i).DAY(:,:) = M_SHELBY(i).DAY(1:end-1,1:6);    
        M_PVSITE(i).RR_1MIN(:,:) = M_SHELBY(i).RR_1MIN(:,1:3);
        M_PVSITE(i).PU(:,:) = M_SHELBY(i).kW(1:end-1,1)./M_PVSITE_INFO.kW;
    end
    load M_SHELBY_SC.mat
    M_PVSITE_SC = M_SHELBY_SC;
    clearvars M_SHELBY_INFO M_SHELBY M_SHELBY_SC
elseif PV_Site == 2
    %MURPHY
    load M_MURPHY_INFO.mat
    M_PVSITE_INFO.RR_distrib = M_MURPHY_INFO.RR_distrib;
    M_PVSITE_INFO.kW = M_MURPHY_INFO.kW;
    M_PVSITE_INFO.name = M_MURPHY_INFO.name;
    load M_MURPHY.mat

    for i=1:1:12
        M_PVSITE(i).DAY(:,:) = M_MURPHY(i).DAY(1:end-1,1:6);    
        M_PVSITE(i).RR_1MIN(:,:) = M_MURPHY(i).RR_1MIN(:,1:3);
        M_PVSITE(i).PU(:,:) = M_MURPHY(i).kW(1:end-1,1)./M_PVSITE_INFO.kW;
    end
    clearvars M_MURPHY_INFO M_MURPHY
elseif PV_Site == 3
    %TAYLOR
    load M_TAYLOR_INFO.mat
    M_PVSITE_INFO.RR_distrib = M_TAYLOR_INFO.RR_distrib;
    M_PVSITE_INFO.kW = M_TAYLOR_INFO.kW;
    M_PVSITE_INFO.name = M_TAYLOR_INFO.name;
    load M_TAYLOR.mat

    for i=1:1:12
        M_PVSITE(i).DAY(:,:) = M_TAYLOR(i).DAY(1:end-1,1:6);    
        M_PVSITE(i).RR_1MIN(:,:) = M_TAYLOR(i).RR_1MIN(:,1:3);
        M_PVSITE(i).PU(:,:) = M_TAYLOR(i).kW(1:end-1,1)./M_PVSITE_INFO.kW;
    end
    clearvars M_TAYLOR_INFO M_TAYLOR
elseif PV_Site == 4
    %Main one that should be used...
    load M_TAYLOR_INFO.mat
    load M_MOCKS_INFO.mat
    M_PVSITE_INFO.RR_distrib = M_MOCKS_INFO.RR_distrib;
    M_PVSITE_INFO.kW = M_MOCKS_INFO.kW;
    M_PVSITE_INFO.name = M_MOCKS_INFO.name;
    M_PVSITE_INFO.VI = M_TAYLOR_INFO.VI;
    M_PVSITE_INFO.CI = M_TAYLOR_INFO.CI;
    load M_MOCKS.mat

    for i=1:1:12
        M_PVSITE(i).DAY(:,:) = M_MOCKS(i).DAY(1:end-1,1:6);    
        M_PVSITE(i).RR_1MIN(:,:) = M_MOCKS(i).RR_1MIN(:,1:3);
        M_PVSITE(i).PU(:,:) = M_MOCKS(i).kW(1:end-1,1)./M_PVSITE_INFO.kW;
    end
    load M_MOCKS_SC.mat
    M_PVSITE_SC = M_MOCKS_SC;
    clearvars M_MOCKS_INFO M_MOCKS M_TAYLOR_INFO M_MOCKS_SC
elseif PV_Site == 5
    load M_AROCK_INFO.mat
    M_PVSITE_INFO.RR_distrib = M_AROCK_INFO.RR_distrib;
    M_PVSITE_INFO.kW = M_AROCK_INFO.kW;
    M_PVSITE_INFO.name = M_AROCK_INFO.name;
    load M_AROCK.mat

    for i=1:1:12
        M_PVSITE(i).DAY(:,:) = M_AROCK(i).DAY(1:end-1,1:6);    
        M_PVSITE(i).RR_1MIN(:,:) = M_AROCK(i).RR_1MIN(:,1:3);
        M_PVSITE(i).PU(:,:) = M_AROCK(i).kW(1:end-1,1)./M_PVSITE_INFO.kW;
    end
    clearvars M_AROCK_INFO M_AROCK

elseif PV_Site == 6
    load M_ODOM_INFO.mat
    M_PVSITE_INFO.RR_distrib = M_ODOM_INFO.RR_distrib;
    M_PVSITE_INFO.kW = M_ODOM_INFO.kW;
    M_PVSITE_INFO.name = M_ODOM_INFO.name;
    load M_ODOM.mat

    for i=1:1:12
        M_PVSITE(i).DAY(:,:) = M_ODOM(i).DAY(1:end-1,1:6);    
        M_PVSITE(i).RR_1MIN(:,:) = M_ODOM(i).RR_1MIN(:,1:3);
        M_PVSITE(i).PU(:,:) = M_ODOM(i).kW(1:end-1,1)./M_PVSITE_INFO.kW;
    end
    clearvars M_ODOM_INFO M_ODOM
elseif PV_Site == 7
    load M_MAYB_INFO.mat
    M_PVSITE_INFO.RR_distrib = M_MAYB_INFO.RR_distrib;
    M_PVSITE_INFO.kW = M_MAYB_INFO.kW;
    M_PVSITE_INFO.name = M_MAYB_INFO.name;
    load M_MAYB.mat

    for i=1:1:12
        M_PVSITE(i).DAY(:,:) = M_MAYB(i).DAY(1:end-1,1:6);    
        M_PVSITE(i).RR_1MIN(:,:) = M_MAYB(i).RR_1MIN(:,1:3);
        M_PVSITE(i).PU(:,:) = M_MAYB(i).kW(1:end-1,1)./M_PVSITE_INFO.kW;
    end
    clearvars M_MAYB_INFO M_MAYB
end